name: Build sing-box-subscribe image 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Build Docker image (on PR)
      if: github.event_name == 'pull_request'
      uses: docker/build-push-action@v4
      with:
          context: .
          tags: sing-box-subscribe:pr-$(date +%s)
          platforms: linux/amd64
          
    - name: Save Docker image as artifact (on PR)
      if: github.event_name == 'pull_request'
      run: |
          IMAGE_ID=$(docker images --format "{{.ID}}" sing-box-subscribe:pr-*)
          docker save -o sing-box-subscribe.tar $IMAGE_ID    
          
    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: sing-box-subscribe-docker-image
        path: sing-box-subscribe.tar
