name: Build sing-box-subscribe image 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Save Docker image as artifact
      run: |
        IMAGE_ID=$(docker images --format "{{.ID}}" my-image-name)
        docker save -o my-image.tar $IMAGE_ID
          
    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-docker-image
        path: my-image.tar
