name: Build sing-box-subscribe Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t sing-box-subscribe:$(date +%s) .
          docker save sing-box-subscribe -o sing-box-subscribe.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sing-box-subscribe-docker-image
          path: sing-box-subscribe.tar
